package com.mythbreak.enums;

public enum NotificationType {
    APPLICATION_SUBMITTED,
    APPLICATION_SHORTLISTED,
    APPLICATION_REJECTED,
    APPLICATION_SELECTED,
    COURSE_ENROLLED,
    COURSE_COMPLETED,
    OPPORTUNITY_POSTED,
    GENERAL
}
